/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ShoppingAddress {
  billing_address?: BaseAddressProps;
  shipping_address?: BaseAddressProps;
  phone_number?: string;
}
export interface BaseAddressProps {
  street_address: string;
  city: string;
  state: string;
}
